# Generated by Django 5.2.1 on 2025-06-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparacaoClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(choices=[('1', 'Temperatura'), ('2', 'Pluviosidade')], max_length=50)),
                ('cidade', models.CharField(choices=[('Americana', 'Americana'), ("Santa Bárbara d'Oeste", "Santa Bárbara d'Oeste"), ('Nova Odessa', 'Nova Odessa'), ('Sumaré', 'Sumaré'), ('Hortolândia', 'Hortolândia'), ('Limeira', 'Limeira'), ('Piracicaba', 'Piracicaba'), ('Campinas', 'Campinas')], max_length=50)),
                ('mes', models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2)),
                ('ano1', models.IntegerField(choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')])),
                ('ano2', models.IntegerField(choices=[(2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')])),
                ('resultadoDispersao', models.JSONField(blank=True, null=True)),
                ('dataConsulta', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
